<a href="https://colab.research.google.com/github/sammanfatima/Pytorch-Journey/blob/main/01_Initializing_tensors%2C_maths%2C_indexing%2C_reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install torch

In [ ]:
import torch
print(torch. __version__)

2.9.0+cu126


### ***Initializing Tensors***

* These are multi dimensional arrays
* Used for storing data so computer can work with it
* Fast computation
* In PyTorch, tensors are the basic building block for all computations.

In [ ]:
device =  "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
my_tensors = torch.tensor([[1, 2, 3], [4, 5, 6]] , dtype = torch.float32)
print(my_tensors)
print(my_tensors.dtype)
print(my_tensors.device)
print(my_tensors.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
cpu
torch.Size([2, 3])


### ***Other common initialization method***

* This creates a 2D tensor with 3 rows and 3 columns.

* Each element is random/uninitialized

In [ ]:
x = torch.empty(size=(3, 3))
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [7.0308e-31, 2.8113e-30, 3.5032e-44],
        [9.1014e-42, 0.0000e+00, 1.1241e-29]])


In [ ]:
x = torch.zeros((3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


* Creates a 3×3 tensor.

* Each element is a random number between 0 and 1 (floating point).

* Unlike empty, these are actual random numbers, not garbage from memory.

In [ ]:
x = torch.rand((3, 3))
print(x)

tensor([[0.2326, 0.0384, 0.4218],
        [0.0536, 0.7242, 0.4554],
        [0.8895, 0.5679, 0.4735]])


In [ ]:
x = torch.ones(3, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x = torch.eye(5, 5)
x = torch.arange(start=0, end=5, step=1)
print(x)
print(x.shape)


tensor([0, 1, 2, 3, 4])
torch.Size([5])


* **Linspace** creates a tensor with evenly spaced numbers from start to end.

In [ ]:
x = torch.eye(5, 5)
x= torch.linspace(start=0.1, end=1, steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


* 5 random numbers, mostly near 0, some bigger or smaller randomly

In [ ]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)

tensor([[-0.0829,  0.3034,  0.1597,  1.6268, -1.2598]])


* All numbers between 0 and 1 have the same chance to appear
* Every time you run it, the numbers change randomly

In [ ]:
x= torch.empty(size=(1,5)).uniform_(0, 1)
print(x)

tensor([[0.8523, 0.7129, 0.5943, 0.6076, 0.6412]])


In [ ]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
x = torch.diag(torch.ones(3)*2)
print(x)

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])


In [ ]:
x = torch.diag(torch.ones(3)*4)
print(x)

tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])


### ***How Initialize tensors and convert them into different types float, double, int***

* 0 will print false
* 1 will print as true

In [ ]:
tensor = torch.arange(4)
print(tensor.bool())

tensor([False,  True,  True,  True])


* Saves memory if you don’t need big integers
* Useful in large tensors to reduce storage
* short() → changes the tensor to int16

In [ ]:
tensor = torch.arange(4)
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


* long() → converts a tensor to int64 (64-bit integer)

In [ ]:
tensor = torch.arange(4)
print(tensor.long())

tensor([0, 1, 2, 3])


In [ ]:
tensor = torch.arange(4)
print(tensor.half()) # float 16
print(tensor.float()) # float 32
print(tensor.double()) # float 64

tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


### ***Array to Tensor conversion and vice verse***

In [ ]:
import numpy as np
np_array = np.zeros((5, 5))
print(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


* NumPy arrays → only run on CPU → normal speed
* PyTorch tensors → can run on GPU → super fast for big calculations
* That’s why in PyTorch we convert NumPy arrays to tensors when we want fast computations or deep learning

In [ ]:
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [ ]:
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### ***Tensor Maths and Comaprison Opertions***

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([7, 8, 9])

In [ ]:
z = x + y
print(z)

tensor([ 8, 10, 12])


In [ ]:
# addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)


tensor([ 8., 10., 12.])


In [ ]:
z2 = torch.add(x, y)
print(z2)

tensor([ 8, 10, 12])


In [ ]:
# subtraction
z = x - y
print(z)

tensor([-6, -6, -6])


In [ ]:
# divide
z = torch.true_divide(x, y)
print(z)

tensor([0.1429, 0.2500, 0.3333])


In [ ]:
# multiply
z = x * y
print(z)

tensor([ 7, 16, 27])
