<a href="https://colab.research.google.com/github/sammanfatima/Pytorch-Journey/blob/main/01_Initializing_tensors%2C_maths%2C_indexing%2C_reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install torch

In [ ]:
import torch
print(torch. __version__)

2.9.0+cu126


### ***Initializing Tensors***

* These are multi dimensional arrays
* Used for storing data so computer can work with it
* Fast computation
* In PyTorch, tensors are the basic building block for all computations.

In [ ]:
device =  "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
my_tensors = torch.tensor([[1, 2, 3], [4, 5, 6]] , dtype = torch.float32)
print(my_tensors)
print(my_tensors.dtype)
print(my_tensors.device)
print(my_tensors.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
cpu
torch.Size([2, 3])


### ***Other common initialization method***

* This creates a 2D tensor with 3 rows and 3 columns.

* Each element is random/uninitialized

In [ ]:
x = torch.empty(size=(3, 3))
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  1.7793e-19],
        [ 0.0000e+00,  2.0744e-19,  0.0000e+00],
        [-2.2855e-35,  4.5381e-41,  1.4013e-45]])


In [ ]:
x = torch.zeros((3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


* Creates a 3×3 tensor.

* Each element is a random number between 0 and 1 (floating point).

* Unlike empty, these are actual random numbers, not garbage from memory.

In [ ]:
x = torch.rand((3, 3))
print(x)

tensor([[0.3499, 0.0987, 0.0226],
        [0.1210, 0.5012, 0.3035],
        [0.3045, 0.5301, 0.7369]])


In [ ]:
x = torch.ones(3, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
x = torch.eye(5, 5)
x = torch.arange(start=0, end=5, step=1)
print(x)
print(x.shape)


tensor([0, 1, 2, 3, 4])
torch.Size([5])


* **Linspace** creates a tensor with evenly spaced numbers from start to end.

In [ ]:
x = torch.eye(5, 5)
x= torch.linspace(start=0.1, end=1, steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


* 5 random numbers, mostly near 0, some bigger or smaller randomly

In [ ]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)

tensor([[-0.4934, -1.3000,  1.0690, -0.6861, -0.7192]])


* All numbers between 0 and 1 have the same chance to appear
* Every time you run it, the numbers change randomly

In [ ]:
x= torch.empty(size=(1,5)).uniform_(0, 1)
print(x)

tensor([[0.6050, 0.9781, 0.2267, 0.6238, 0.4038]])


In [ ]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
x = torch.diag(torch.ones(3)*2)
print(x)

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])


In [ ]:
x = torch.diag(torch.ones(3)*4)
print(x)

tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])


### ***How Initialize tensors and convert them into different types float, double, int***

* 0 will print false
* 1 will print as true

In [ ]:
tensor = torch.arange(4)
print(tensor.bool())

tensor([False,  True,  True,  True])


* Saves memory if you don’t need big integers
* Useful in large tensors to reduce storage
* short() → changes the tensor to int16

In [ ]:
tensor = torch.arange(4)
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


* long() → converts a tensor to int64 (64-bit integer)

In [ ]:
tensor = torch.arange(4)
print(tensor.long())

tensor([0, 1, 2, 3])


In [ ]:
tensor = torch.arange(4)
print(tensor.half()) # float 16
print(tensor.float()) # float 32
print(tensor.double()) # float 64

tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


### ***Array to Tensor conversion and vice verse***

In [ ]:
import numpy as np
np_array = np.zeros((5, 5))
print(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


* NumPy arrays → only run on CPU → normal speed
* PyTorch tensors → can run on GPU → super fast for big calculations
* That’s why in PyTorch we convert NumPy arrays to tensors when we want fast computations or deep learning

In [ ]:
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [ ]:
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### ***Tensor Maths and Comaprison Opertions***

In [ ]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([7, 8, 9])

In [ ]:
z = x + y
print(z)

tensor([ 8, 10, 12])


In [ ]:
# addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)


tensor([ 8., 10., 12.])


In [ ]:
z2 = torch.add(x, y)
print(z2)

tensor([ 8, 10, 12])


In [ ]:
# subtraction
z = x - y
print(z)

tensor([-6, -6, -6])


In [ ]:
# divide
z = torch.true_divide(x, y)
print(z)

tensor([0.1429, 0.2500, 0.3333])


In [ ]:
# multiply
z = x * y
print(z)

tensor([ 7, 16, 27])


In [ ]:
# divison
x = torch.tensor([2.0, 4.0, 8.0])
y = torch.tensor([2.0, 2.0, 2.0])
z = torch.true_divide(x, y)
print(z)

tensor([1., 2., 4.])


In [ ]:
# inplace operation
t = torch.zeros(3)
t.add_(x)
t += x
print(t)

tensor([ 4.,  8., 16.])


In [ ]:
# exponential
z = x.pow(2)
print(z)

tensor([ 4, 16, 64])


In [ ]:
#simple comaprison
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [ ]:
# matrix multiplication
x1 = torch.rand(2,5)
print(x1)
x2 = torch.rand(5,2)
print(x2)
x3 = torch.mm(x1,x2)
print(x3)

tensor([[0.8137, 0.3662, 0.1357, 0.3415, 0.5439],
        [0.4537, 0.9490, 0.8661, 0.1781, 0.7599]])
tensor([[0.6112, 0.5612],
        [0.6770, 0.2733],
        [0.4530, 0.6152],
        [0.7201, 0.1691],
        [0.6691, 0.3910]])
tensor([[1.4165, 0.9106],
        [1.9487, 1.3740]])


In [ ]:
x3 = x1.mm(x2)
print(x3)

tensor([[1.4165, 0.9106],
        [1.9487, 1.3740]])


In [ ]:
# matrix exponentiation
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3)
print(matrix_exp)

tensor([[0.5035, 0.6156, 0.0384, 0.3872, 0.8785],
        [0.8341, 0.3586, 0.1970, 0.1145, 0.7315],
        [0.4423, 0.4941, 0.1154, 0.4363, 0.7333],
        [0.4988, 0.1735, 0.6542, 0.7379, 0.9259],
        [0.1143, 0.0277, 0.9399, 0.2048, 0.3553]])


In [ ]:
# element wise multiplication
z = x * y
print(z)

tensor([ 4.,  8., 16.])


In [ ]:
# dot prod
x = torch.tensor([3])
y = torch.tensor([2])
z = torch.dot(x, y)
print(z)

tensor(6)


### **Batch matrix** **multiplication**

* Performing multiple matrix multiplications at once in a single operation.
* You have multiple matrices, and you multiply all of them in one single operation.

In [ ]:
# batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm)


tensor([[[5.6655, 3.8963, 4.2434,  ..., 3.8507, 4.5226, 5.6138],
         [6.3879, 4.0415, 4.3344,  ..., 4.6911, 4.6140, 5.9356],
         [7.4438, 4.9019, 5.4600,  ..., 4.9914, 5.0852, 6.7301],
         ...,
         [5.2086, 2.9990, 3.3563,  ..., 3.5676, 3.8371, 4.5896],
         [5.6706, 4.1147, 4.3690,  ..., 4.3408, 3.3937, 4.9474],
         [4.4523, 2.7628, 3.1773,  ..., 3.3094, 3.6006, 3.7920]],

        [[6.2186, 5.8357, 5.8269,  ..., 6.0166, 5.8246, 4.9747],
         [4.2761, 4.1781, 4.8795,  ..., 5.2201, 4.4274, 4.2266],
         [4.6531, 4.2287, 4.6714,  ..., 4.4417, 4.3060, 3.0978],
         ...,
         [5.1752, 4.3064, 4.1303,  ..., 4.7481, 4.6445, 3.4737],
         [5.1496, 4.3903, 5.7399,  ..., 5.3910, 4.9819, 4.6122],
         [5.7119, 4.8455, 5.4007,  ..., 5.2276, 5.2171, 4.6220]],

        [[5.5645, 5.4277, 5.5855,  ..., 5.8036, 6.0347, 5.9405],
         [4.8101, 4.8088, 4.6830,  ..., 3.9975, 4.8479, 4.9771],
         [5.0994, 4.6436, 5.4203,  ..., 5.2439, 4.9309, 5.

In [ ]:
#braodcasting
x = torch.rand((5,5))
y = torch.rand((1,5))
z = x - y
print(z)
z = x ** y
print(z)

tensor([[-0.5319,  0.5927,  0.3908,  0.5301,  0.0861],
        [-0.6206, -0.0645,  0.1588,  0.3137,  0.2222],
        [-0.1069,  0.6591, -0.2121,  0.8567, -0.5634],
        [-0.5723,  0.0617, -0.2116,  0.4068, -0.2371],
        [-0.3760,  0.5431,  0.2164,  0.2334,  0.3733]])
tensor([[0.2891, 0.9558, 0.9312, 0.9625, 0.7969],
        [0.1730, 0.6882, 0.8036, 0.9305, 0.8882],
        [0.6952, 0.9686, 0.5284, 0.9947, 0.1338],
        [0.2392, 0.7879, 0.5289, 0.9459, 0.5437],
        [0.4558, 0.9456, 0.8374, 0.9143, 0.9828]])


# ***Tensor Indexing***

In [ ]:
batch_size = 10 # 10 samples processed together
features = 25 # features are col and in each col there are 25 elements
x = torch.rand((batch_size ,features))
print(x)
print(x[0])
print(x[0].shape) # tells you how many elements are in that row

tensor([[0.9111, 0.9099, 0.6351, 0.9879, 0.1930, 0.4262, 0.7860, 0.0012, 0.2957,
         0.9522, 0.4619, 0.0104, 0.4593, 0.1692, 0.9920, 0.1117, 0.6039, 0.2474,
         0.0744, 0.6075, 0.6930, 0.9784, 0.2762, 0.6079, 0.2723],
        [0.1558, 0.1750, 0.4487, 0.5149, 0.2013, 0.7311, 0.0289, 0.8091, 0.8130,
         0.8797, 0.3599, 0.8017, 0.2608, 0.8730, 0.1551, 0.5209, 0.3946, 0.9413,
         0.9142, 0.8252, 0.6595, 0.9184, 0.5374, 0.4062, 0.8773],
        [0.9884, 0.8825, 0.6672, 0.6636, 0.9941, 0.4100, 0.0347, 0.7496, 0.2159,
         0.8648, 0.6038, 0.0387, 0.1141, 0.6330, 0.7153, 0.5128, 0.5585, 0.3374,
         0.8010, 0.7608, 0.2182, 0.7505, 0.3863, 0.4551, 0.2664],
        [0.2997, 0.6876, 0.3472, 0.3827, 0.3286, 0.7490, 0.6548, 0.1985, 0.8207,
         0.2296, 0.3636, 0.7248, 0.5369, 0.2353, 0.4259, 0.6047, 0.3307, 0.5030,
         0.1316, 0.0609, 0.2016, 0.4266, 0.8047, 0.1013, 0.5089],
        [0.6511, 0.7374, 0.0476, 0.9736, 0.6319, 0.7196, 0.0262, 0.4293, 0.3871,
       

In [ ]:
print(x[:, 0].shape)
print(x[2 , 0:10].shape)

torch.Size([10])
torch.Size([10])


In [ ]:
# fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x[indices])

tensor([2, 5, 8])


In [ ]:
x = torch.rand(3,5)
rows = torch.tensor([1, 0])
col = torch.tensor([4,0])
print(x[rows, col])
print(x[rows, col].shape)

tensor([0.4580, 0.3646])
torch.Size([2])
